// Generated by gencpp from file leg_tracker/Leg.msg
// DO NOT EDIT!


#ifndef LEG_TRACKER_MESSAGE_LEG_H
#define LEG_TRACKER_MESSAGE_LEG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace leg_tracker
{
template <class ContainerAllocator>
struct Leg_
{
  typedef Leg_<ContainerAllocator> Type;

  Leg_()
    : position()
    , confidence(0.0)  {
    }
  Leg_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::leg_tracker::Leg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leg_tracker::Leg_<ContainerAllocator> const> ConstPtr;

}; // struct Leg_

typedef ::leg_tracker::Leg_<std::allocator<void> > Leg;

typedef boost::shared_ptr< ::leg_tracker::Leg > LegPtr;
typedef boost::shared_ptr< ::leg_tracker::Leg const> LegConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leg_tracker::Leg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leg_tracker::Leg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leg_tracker::Leg_<ContainerAllocator1> & lhs, const ::leg_tracker::Leg_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leg_tracker::Leg_<ContainerAllocator1> & lhs, const ::leg_tracker::Leg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leg_tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::Leg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::Leg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::Leg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::Leg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::Leg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::Leg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leg_tracker::Leg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8000af3463f92157ee303c820e3b02c6";
  }

  static const char* value(const ::leg_tracker::Leg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8000af3463f92157ULL;
  static const uint64_t static_value2 = 0xee303c820e3b02c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::leg_tracker::Leg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leg_tracker/Leg";
  }

  static const char* value(const ::leg_tracker::Leg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leg_tracker::Leg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Position and confidence of a leg \n"
"geometry_msgs/Point position\n"
"float32 confidence\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::leg_tracker::Leg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leg_tracker::Leg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Leg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leg_tracker::Leg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leg_tracker::Leg_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEG_TRACKER_MESSAGE_LEG_H
