// Generated by gencpp from file leg_tracker/LegArray.msg
// DO NOT EDIT!


#ifndef LEG_TRACKER_MESSAGE_LEGARRAY_H
#define LEG_TRACKER_MESSAGE_LEGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <leg_tracker/Leg.h>

namespace leg_tracker
{
template <class ContainerAllocator>
struct LegArray_
{
  typedef LegArray_<ContainerAllocator> Type;

  LegArray_()
    : header()
    , legs()  {
    }
  LegArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , legs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::leg_tracker::Leg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::leg_tracker::Leg_<ContainerAllocator> >::other >  _legs_type;
  _legs_type legs;





  typedef boost::shared_ptr< ::leg_tracker::LegArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leg_tracker::LegArray_<ContainerAllocator> const> ConstPtr;

}; // struct LegArray_

typedef ::leg_tracker::LegArray_<std::allocator<void> > LegArray;

typedef boost::shared_ptr< ::leg_tracker::LegArray > LegArrayPtr;
typedef boost::shared_ptr< ::leg_tracker::LegArray const> LegArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leg_tracker::LegArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leg_tracker::LegArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leg_tracker::LegArray_<ContainerAllocator1> & lhs, const ::leg_tracker::LegArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.legs == rhs.legs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leg_tracker::LegArray_<ContainerAllocator1> & lhs, const ::leg_tracker::LegArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leg_tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::LegArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::LegArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::LegArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::LegArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::LegArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::LegArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leg_tracker::LegArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e932f47090c69cbf30f535c2ab02e32";
  }

  static const char* value(const ::leg_tracker::LegArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e932f47090c69cbULL;
  static const uint64_t static_value2 = 0xf30f535c2ab02e32ULL;
};

template<class ContainerAllocator>
struct DataType< ::leg_tracker::LegArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leg_tracker/LegArray";
  }

  static const char* value(const ::leg_tracker::LegArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leg_tracker::LegArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Array of legs \n"
"std_msgs/Header header\n"
"Leg[] legs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: leg_tracker/Leg\n"
"# Position and confidence of a leg \n"
"geometry_msgs/Point position\n"
"float32 confidence\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::leg_tracker::LegArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leg_tracker::LegArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.legs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leg_tracker::LegArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leg_tracker::LegArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "legs[]" << std::endl;
    for (size_t i = 0; i < v.legs.size(); ++i)
    {
      s << indent << "  legs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::leg_tracker::Leg_<ContainerAllocator> >::stream(s, indent + "    ", v.legs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEG_TRACKER_MESSAGE_LEGARRAY_H
