// Generated by gencpp from file leg_tracker/Person.msg
// DO NOT EDIT!


#ifndef LEG_TRACKER_MESSAGE_PERSON_H
#define LEG_TRACKER_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace leg_tracker
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : pose()
    , id(0)  {
    }
  Person_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::leg_tracker::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leg_tracker::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::leg_tracker::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::leg_tracker::Person > PersonPtr;
typedef boost::shared_ptr< ::leg_tracker::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leg_tracker::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leg_tracker::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leg_tracker::Person_<ContainerAllocator1> & lhs, const ::leg_tracker::Person_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leg_tracker::Person_<ContainerAllocator1> & lhs, const ::leg_tracker::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leg_tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leg_tracker::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f334171b5664340c323a1982b554a22";
  }

  static const char* value(const ::leg_tracker::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f334171b5664340ULL;
  static const uint64_t static_value2 = 0xc323a1982b554a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::leg_tracker::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leg_tracker/Person";
  }

  static const char* value(const ::leg_tracker::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leg_tracker::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Pose of a person\n"
"geometry_msgs/Pose pose\n"
"uint32 id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::leg_tracker::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leg_tracker::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leg_tracker::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leg_tracker::Person_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEG_TRACKER_MESSAGE_PERSON_H
