// Generated by gencpp from file leg_tracker/PersonArray.msg
// DO NOT EDIT!


#ifndef LEG_TRACKER_MESSAGE_PERSONARRAY_H
#define LEG_TRACKER_MESSAGE_PERSONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <leg_tracker/Person.h>

namespace leg_tracker
{
template <class ContainerAllocator>
struct PersonArray_
{
  typedef PersonArray_<ContainerAllocator> Type;

  PersonArray_()
    : header()
    , people()  {
    }
  PersonArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , people(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::leg_tracker::Person_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::leg_tracker::Person_<ContainerAllocator> >::other >  _people_type;
  _people_type people;





  typedef boost::shared_ptr< ::leg_tracker::PersonArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leg_tracker::PersonArray_<ContainerAllocator> const> ConstPtr;

}; // struct PersonArray_

typedef ::leg_tracker::PersonArray_<std::allocator<void> > PersonArray;

typedef boost::shared_ptr< ::leg_tracker::PersonArray > PersonArrayPtr;
typedef boost::shared_ptr< ::leg_tracker::PersonArray const> PersonArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leg_tracker::PersonArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leg_tracker::PersonArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::leg_tracker::PersonArray_<ContainerAllocator1> & lhs, const ::leg_tracker::PersonArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.people == rhs.people;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::leg_tracker::PersonArray_<ContainerAllocator1> & lhs, const ::leg_tracker::PersonArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace leg_tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::PersonArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_tracker::PersonArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::PersonArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_tracker::PersonArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::PersonArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_tracker::PersonArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leg_tracker::PersonArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b54bf6148ab21083b85a27eec643002";
  }

  static const char* value(const ::leg_tracker::PersonArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b54bf6148ab2108ULL;
  static const uint64_t static_value2 = 0x3b85a27eec643002ULL;
};

template<class ContainerAllocator>
struct DataType< ::leg_tracker::PersonArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leg_tracker/PersonArray";
  }

  static const char* value(const ::leg_tracker::PersonArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leg_tracker::PersonArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Array of person positions\n"
"std_msgs/Header header\n"
"Person[] people\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: leg_tracker/Person\n"
"# Pose of a person\n"
"geometry_msgs/Pose pose\n"
"uint32 id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::leg_tracker::PersonArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leg_tracker::PersonArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.people);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leg_tracker::PersonArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leg_tracker::PersonArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "people[]" << std::endl;
    for (size_t i = 0; i < v.people.size(); ++i)
    {
      s << indent << "  people[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::leg_tracker::Person_<ContainerAllocator> >::stream(s, indent + "    ", v.people[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEG_TRACKER_MESSAGE_PERSONARRAY_H
